spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE

acquirer:
  base-url: "http://localhost:9090"
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
#hibernate:
#  show_sql: true